---
title: "New York State Weather Stations Dashboard - Jan. 15 and June 15 of each year from 2000 to 2010"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r, include=FALSE}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, sep = "-", into = c("year", "month", "day")) %>%
  mutate_at(c(2:9), as.numeric) %>% 
  mutate(prcp = prcp/10) %>% 
  mutate(tmin = tmin/10, tmax = tmax/10) %>% 
  mutate(month = month.name[as.numeric(month)]) %>% 
  filter(
    day == 15,
    year >= 2000,
    prcp != 0,
    month %in% c("January", "June")) %>% 
  drop_na(tmin, tmax)
ny_noaa

```


Column {data-width=650}
-----------------------------------------------------------------------

### Minimum and Maximum temperatures in January and June by NY weather station

```{r}
ny_noaa %>%
  mutate(
    text_label = str_c("ID: ", id, "\nYear: ", year)) %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~month,
    type = "scatter", mode = "markers",
    alpha = .5, text = ~text_label) %>%
    layout(xaxis = list(title = 'Minimum Temperature (°C)'), font=t, plot_bgcolor = "#e5ecf6",
           yaxis = list(title = 'Maximum Temperature (°C)'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Summary of minimum temperatures in January and June

```{r}
ny_noaa %>%
  plot_ly(
    y = ~tmin, color = ~month,
          type = "box", colors = "viridis") %>%
    layout(xaxis = list(title = 'Month'), font=t, plot_bgcolor = "#e5ecf6",
           yaxis = list(title = 'Minimum Temperature (°C)'))
```

### Counts of precipitation numbers that is 30 mm or less

```{r}
ny_noaa %>%
  filter(prcp <= 30) %>% 
  count(prcp) %>%
  mutate(text_label = str_c("Precip: ", prcp, "\nCount: ", n)) %>% 
  plot_ly(
    x = ~prcp, y = ~n,
    type = "bar", text = ~text_label) %>%
    layout(xaxis = list(title = 'Precipitation (mm)'), font=t, plot_bgcolor = "#e5ecf6",
           yaxis = list(title = 'Count'))
```

