---
#title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

&nbsp;

## Education:

**Columbia University Mailman School of Public Health - New York, NY**  
May 2023  
Master of Public Health in Epidemiology, Certificate in Infectious Disease Epidemiology  
Columbia Public Health Scholarship Award  

	
**Rutgers University - New Brunswick, NJ**  
May 2020  
Bachelor of Science in Public Health, Minor in Biological Sciences, Certificate in Health Disparities  
Magna Cum Laude, Highest Honors, and Dean’s List  


&nbsp;


## Work Experiences:


**Cardiovascular Digital Health Lab, NYU Langone Health - New York, NY**  
August 2023 - present  
Data Analyst  

* Lead the management of multiple database projects for 4+ clinical trials using a research and statistical framework for complex health research data up to the reporting standards of the NIH 
* Prepare interim reports and conduct statistical analysis in R and SAS for timely reporting of accurate data to the team and collaborators
* Contribute in the development of publications and conference materials, including drafting manuscripts, abstracts, and data visualizations 


**Columbia University Mailman School of Public Health - New York, NY**         
April 2023 - June 2023  
Epidemiology Student Researcher  

* Developed methods for improved visual aids such as tables and graphs of statistical outputs from analysis on COVID-19 and air pollution in R using the ggplot package
* Collaborated with research members on refining documentation for grant submission and acceptance 


**Herbert Irving Comprehensive Cancer Center, NYP/CUIMC – New York, NY**    
July 2022 – May 2023  
Recruiter and Data Analyst for the DISCover cohort  							

* Built and maintained a repository of biological samples, clinical data, and epidemiological data of more than 7000 patients who were at risk or had cancer
* Coordinated health research activities such as collection and transfer of blood, saliva, tissues, and other bio specimens for bio marker analysis, adding to more than 4000 accumulated bio specimens
* Cleaned and analyzed data that has been collected from 3800+ questionnaires and the electronic health records (EHR) of individuals consented to the DBSR protocol


**Public Health Environmental Laboratories, NJ Department of Health - Ewing, NJ**  
January 2020 – May 2020  
Molecular Virology Intern  

* Improved the surveillance informatics system of the Molecular Virology department by creating an interactive database of over 400 historical arboviral and influenza specimens stored in the freezers and merged qualitative data of test results from JerseySurv (VectorSurv) with the new database
* Attained knowledge of the routine lab procedures by shadowing extractions and PCR tests  
* Surveyed for geographic trends by NJ county in positive influenza specimens


**Institute for Health, Health Care Policy, and Aging Research - New Brunswick, NJ**  
Summer 2019  
Community Engagement Project Intern 

* Evaluated the history of CBPR in the African American population via literature searches
* Composed a reference list of over 20 African American organizations based in NJ that  
serve or advocate for this community   
* Established points of communication with these organizations via emails and phone calls to discuss opportunities for future collaborations 
*  Engaged in journal club by analyzing peer-reviewed, scientific articles and participating in discussions of the assigned text
*  Participated in holistic seminar series led by distinguished faculty of the Institute to explore research processes and possibilities


&nbsp;


## Certifications/Trainings:

* Preconception Peer Educator certified – US Department of Health and Human Services, Office of Minority Health 
* CITI program certifications: Good Clinical Practice (GCP), Clinical Research Coordinator (CRC), Human Subjects Protection Training, HIPAA, Bloodborne Pathogens, FDA Regulated Research  
* NYC DOHMH Team Epi Outbreak Investigator 

&nbsp;


## Skills:

* Software skills: Screening Center on Specimen Gate, JerseySurv (VectorSurv), EPIC, Velos, Qualtrics, GitHub, REDCap
* Statistical software skills: SAS, R, R Markdown, Flex-dashboards, Plotly, Shiny App, QGIS, GeoDa, SaTScan
* Microsoft Office (Word, PowerPoint, Excel) 
* Literature Reviews 
* Public Speaking 
* Writing skills via development of lab reports and research papers 
* Meticulous, detail oriented, organized 

&nbsp;

## Publications & Projects:

* [Rehabilitation at Home Using Mobile Health in Older Adults After Hospitalization for Ischemic Heart Disease: The RESILIENT Randomized Clinical Trial](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2828802)
  - A NIA/NIH funded randomized clinical trial (RCT) examining mobile health cardiac rehabilitation in adults with ischemic heart disease
  - Published in JAMA Network Open in January 2025
  - Presented at the 2024 European Society of Cardiology (ESC) Congress in London
* [Assessing Sex Differences in the Relationship Between Social Isolation and Incident Atherosclerotic Cardiovascular Disease and Death Using Data from the U.S. Health and Retirement Study](https://www.ahajournals.org/doi/10.1161/circ.150.suppl_1.4134572)
  - Published in Circulation in November 2024
  - Presented at American Heart Association (AHA) 2024 Scientific Session
* [Angina Among Older Adults With Ischemic Heart Disease: Findings From The RESILIENT Trial](https://www.jacc.org/doi/abs/10.1016/S0735-1097%2825%2902971-7)
  - Published in JACC in March 2025
  - Presented at ACC 2025
* Imaging analysis of hepatic abnormalities in adults with congenital heart disease
  - Presented at 34th Annual International Symposium on Adults with Congenital Heart Disease in June 2025 in Toronto, Canada
* Master’s Thesis: Pancreatic cancer risk and the DASH diet, in collaboration with Harvard University’s Pooling Project of Prospective Studies of Diet and Cancer
* Analysis of NHANES 2015-2016 data: The association of ever being diagnosed with having an STI with  age at first intercourse 


